[lint]
select = [
  "E",    # pycodestyle errors
  "F",    # pyflakes
  "I",    # import sorting
  "B",    # bugbear (common bugs & pitfalls)
  "UP",   # pyupgrade (modern syntax)
  "RUF",  # Ruff-specific rules (extra checks)
]

# Disable all docstring-related rules
ignore = [
  "E203",   # whitespace before ':' (Black-compatible)
  "E266",   # too many leading '#' for block comment
  "E501",   # line too long (formatter handles this)
  "D",      # ALL pydocstyle rules
  "RUF002", # docstring ambiguous hyphen (already covered by D)
  "RUF003", # docstring invalid escape sequences
]

